### ISSUE TITLE
[FEATURE]: As a toolkit user, I want to have an integrated Streamlit app in the toolkit, so I can see a data visualization inside the toolkit itself.

### ISSUE THREAD

**Issue by leiyakenney** [RebootMotion/reboot-toolkit#28]
## Description

Create a Streamlit App for Toolkit and Dashboard integration that allows users to visualize data inside the toolkit itself

## Motivation & Context

Better user experience

## Acceptance Criteria

Streamlit app is created and is integrated into the Toolkit (to be integrated into the Dashboard later)

## Definition of Done

Streamlit app is created and is integrated into the Toolkit (to be integrated into the Dashboard later)

**Comment by leiyakenney** [comment]
@jimmybuffi @RobertCalise 
It looks like adding Streamlit or Mercury would improve the user experience a bit, but definitely nothing life-changing for more experienced coders. They are more so used for things like creating apps like the one I showed on Sprint Review today with the dropdowns etc for people who don't want to/can't update the code themselves, which doesn't really sound like what we're wanting to do. 

Here are screenshots of the outputs from the Jupyter Notebook using both: 

Streamlit: 
<img width="1030" alt="Screenshot 2023-09-27 at 12 52 07" src="https://github.com/RebootMotion/reboot-toolkit/assets/45922590/fa9a3229-f4c2-4904-8e7b-79beeee9e1e1">

Mercury: 
<img width="1262" alt="Screenshot 2023-09-27 at 12 51 59" src="https://github.com/RebootMotion/reboot-toolkit/assets/45922590/03ad7db4-a385-49fc-8f05-c326b26d8f4c">

Would love to hear your thoughts on this.

**Comment by jimmybuffi** [comment]
thanks so much @leiyakenney ! i think it's worth discussing this live, so we can all be on the same page regarding the goal

**Comment by leiyakenney** [comment]
@jimmybuffi @RobertCalise 
I worked yesterday on figuring out how to render a Mercury app inside a Jupyter cell and it looks like it's the same situation as Streamlit, so it's possibly doable but maybe more effort than it's worth. 

That being said, I found [this filter.ipynb]( https://colab.research.google.com/github/khuyentran1401/Efficient_Python_tricks_and_tools_for_data_scientists/blob/master/Chapter3/filter.ipynb), which looks promising and works within a Jupyter Notebook cell, as well as [Qgrid](https://github.com/quantopian/qgrid), which is a Jupyter notebook widget that renders pandas dataframes within a Jupyter notebook. 

I personally would like to try out Qgrid, because I feel that it has a better user experience and I think would allow us to have that filtered table for the Pandas dataframe that we want. 

Let me know your thoughts!

**Comment by jimmybuffi** [comment]
Thanks @leiyakenney !

The filter notebook you linked to looks like it's just demoing lots of the pandas filtering functions which are being used under the hood in the toolkit function already. Essentially, the way it works is the widget in the toolkit gets the parameters that should be passed to these pandas filter parameters.

I saw qgrid and I thought it looked promising as well, but as I dug into it, there seemed to be some compatibility issues with the more modern libraries, because qgrid hasn't been updated in a few years. But definitely could be spending a little more time on, even forking it ourselves if we have to (looks like there are lots of forks already!).

As we get deeper into this, I'm thinking the easiest path forward might just be to dive deeper into regular ipywidgets, since those are already meant to do exactly what we need, and see if we can make the experience a lot better.

**Comment by leiyakenney** [comment]
So I've tried many different iterations of ipywidgets with varying levels of success. 

One option is to have dropdowns for each of the selection options instead of the selectors we currently have by using `ipywidgets.Dropdown` or `ipywidget.interact`- this won't change too much from our current toolkit besides just turning all the current selector into dropdowns vs having them be in a list as they currently are though. I guess maybe a nicer experience, but I don't think it's worth switching everything around for. 

**The other option that looks like it might make any real difference** would be to use `interactive` from ipywidgets, which allows you to select multiple filterable categories and it updates the table in real-time. 

If you scroll down to the bottom section ("Using the Interactive Function") of this blog: https://towardsdatascience.com/making-your-data-analytics-come-to-life-using-ipywidgets-cfa9538279f7 it gives a good example of using multiple filters at once to show one dataset that has been filtered and can be updated in real-time using the provided filters. The issue I've found with this one is that it's not really possible to do a "select multiple" in the filters; you can have a "select all" option, but trying to select just a few from one dropdown seems like it might be overly complicated. Since we currently allow a multi-select, not sure if that's something we would be okay with getting rid of for this, but happy to pursue this option if it seems like it would be helpful. 

Also, anywidget definitely looks cool, but it looks like it's better suited to people trying to make their own widgets vs. using what already exists. So I think it's an avenue worth exploring at some point if we decide we want to make our own widget, but I was under the impression we were just trying to use ones that already exist (ideally).

**Comment by leiyakenney** [comment]
Closing this issue as existing widgets don't really do what we were hoping they could do - may be revisited in the future.
